import Head from 'next/head'
import Navbar from '../components/Navbar/Navbar'

export default function Home() {
  return (
    <main>
      <div>
        <Head>
          <title>Next Mobiles</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Navbar />
      </div>
    </main>
  )
}
